### ISSUE TITLE
Reconnect spawns new connection in infinite loop

### ISSUE THREAD

**Issue by lbeuster** [realtime-framework/RealtimeMessaging-Java#18]
Hi,
this issue is the follow-up to a chat on your website today (I am ipool_dev@....de).

The problem was that a reconnect in the client (e.g. because of maintenance of your services) increases the number of connections to the server until the connection limit is reached.

The problem is even more serious than that because the client spawn new websocket connect threads in an infinite loop. This results in an OutOfMemoryError after some time and the application becomes unusable.

The problem is easy to reproduce: create a client, connect (I guess it's important to activate the heartbeat) and let the application sleep. Remove the network connectivity and after some time the client starts to reconnect. Activate the network again -> now we have the infinite loop (and the callbacks are called periodically).

Best regards
Lars

**Comment by realtime-framework** [comment]
Thanks for the heads-up @lbeuster, we'll be looking over this asap.

**Comment by lbeuster** [comment]
Thanks for the fix. I tested my use case too and it worked now ;)
